#Load all needed packages and create MySQL connection

```{r include=FALSE}

packages <- c('useful', 'coefplot', 'xgboost', 'here', 'magrittr', 'dygraphs', 'dplyr', 'RMySQL', 'caret', 'purrr', 'randomForest', 'rpart', 'neuralnet')
purrr::walk(packages, library, character.only = TRUE)
lapply( dbListConnections( dbDriver( drv = "MySQL")), dbDisconnect)
mychannel <- dbConnect(MySQL(), user="root", pass="dave41", host="127.0.0.1")
query <- function(...) dbGetQuery(mychannel, ...)

```


#Load historical data

```{r include=FALSE}
var_whse <- 3
var_build <- 2

sqlquery <- paste("SELECT 
                  CASE
                  WHEN predicted_availhour < 6 THEN 6
                  WHEN predicted_availhour > 16 THEN 16
                  ELSE predicted_availhour
                  END AS HOUR,
                  workday_workday AS WORKDAY,
                  workday_weekofmon AS MONTHWEEK,
                  workday_weekday AS WEEKDAY,
                  workday_dayofmon AS MONTHDAY,
                  workday_month AS MONTH,
                  YEAR(predicted_availdate) as YEAR,
                  workday_befvac AS BEFVAC,
                  workday_aftvac AS AFTVAC,
                  workday_befchrist AS BEFCHRIST,
                  workday_aftchrist AS AFTCHRIST,
                  SUM(CASE
                  WHEN
                  hist_twoday = 1
                  AND predicted_availhour < 6
                  THEN
                  1
                  ELSE 1
                  END) AS BOXES
                  FROM
                  slotting.hist_casevol
                  JOIN
                  slotting.workdayofweek ON predicted_availdate = workday_date
                  WHERE 
                  hist_whse = ",var_whse," and hist_build = ",var_build," 
                  AND hist_equip = 'PALLETJACK'
                  AND cutoff_group NOT IN ('TRUCK' , 'COLGATE')
                  AND predicted_availhour BETWEEN 7 AND 16
                  GROUP BY predicted_availdate , hist_equip, 
                  CASE
                  WHEN predicted_availhour < 6 THEN 6
                  WHEN predicted_availhour > 16 THEN 16
                  ELSE predicted_availhour
                  END
                  ORDER BY predicted_availdate , CASE
                  WHEN predicted_availhour < 6 THEN 6
                  WHEN predicted_availhour > 16 THEN 16
                  ELSE predicted_availhour
                  END", sep = "")
data <- query(sqlquery)

head(data)

```


#Set seed and determine training and test data

```{r include=FALSE}

set.seed(222)
trainIndex <- createDataPartition(data$BOXES, 
                                  p = .75, 
                                  list = FALSE, 
                                  times = 1)

dataTrain <- data[ trainIndex,]
dataTest  <- data[-trainIndex,]

head(dataTrain)
head(dataTest)

data_formula_boxes <- BOXES ~ HOUR + WORKDAY + MONTHWEEK + WEEKDAY + MONTHDAY + MONTH + YEAR + BEFVAC + AFTVAC + BEFCHRIST + AFTCHRIST

#boxes data training
dataX_Train_box <- build.x(data_formula_boxes, data=dataTrain,
                       contrasts=FALSE,
                       sparse=TRUE)
dataY_Train_box <- build.y(data_formula_boxes,data=dataTrain) 

dataX_Test_box <- build.x(data_formula_boxes, data=dataTest,
                      contrasts=FALSE,
                      sparse=TRUE)
dataY_Test_box <- build.y(data_formula_boxes,data=dataTest)

xgTrain_box <- xgb.DMatrix(data=dataX_Train_box,
                       label=dataY_Train_box)

xgVal_box <- xgb.DMatrix(data=dataX_Test_box,
                     label=dataY_Test_box)
```

#Create the Linear regression model

```{r echo=FALSE}
model.lm <- lm(data_formula_boxes, data=dataTrain)
prediction.lm <- predict(model.lm, newdata=dataTest)
rmse.lm <- sqrt(mean((dataTest$BOXES-prediction.lm)^2))
rmse.lm
plot(dataTest$BOXES,prediction.lm,col='blue',main='Real vs predicted Linear Regression',pch=18, cex=0.7)
abline(0,1,lwd=2)

```


#Create the decision tree model

```{r echo=TRUE}

model.dt <- rpart(data_formula_boxes, method = "anova", data=dataTrain)
prediction.dt <- predict(model.dt, newdata = dataTest)
rmse.dt <- sqrt(mean((dataTest$BOXES-prediction.dt)^2))
rmse.dt
plot(dataTest$BOXES,prediction.dt,col='blue',main='Real vs predicted Decision Tree',pch=18, cex=0.7)
abline(0,1,lwd=2)


```


#Create the random forest model
```{r}

dataTrain_fac <- dataTrain %>% mutate_if(is.character, as.factor)
dataTest_fac <- dataTest %>% mutate_if(is.character, as.factor)
model.rf <- randomForest(data_formula_boxes, data = dataTrain_fac)
prediction.rf <- predict(model.rf, newdata = dataTest_fac)
rmse.rf <- sqrt(mean((dataTest_fac$BOXES-prediction.rf)^2))
rmse.rf
plot(dataTest$BOXES,prediction.rf,col='blue',main='Real vs predicted Random Forest',pch=18, cex=0.7)
abline(0,1,lwd=2)

```


#Create the neural net model  ***Clean up the code to match the other chunks***
```{r}
library('neuralnet')

maxs <- apply(dataTrain, 2, max)
mins <- apply(dataTrain, 2, min)
scaled_train <- as.data.frame(scale(dataTrain, center = mins, scale = maxs - mins))
scaled_test <- as.data.frame(scale(dataTest, center = mins, scale = maxs - mins))
n <- names(scaled_train)
f <- as.formula(paste("BOXES ~", paste(n[!n %in% "BOXES"], collapse = " + ")))

nn <- neuralnet(f,data=scaled_train,hidden=c(5,3),linear.output=F)
pr.nn <- compute(nn,scaled_test[,0:11])
pr.nn_ <- pr.nn$net.result*(max(data$BOXES)-min(data$BOXES))+min(data$BOXES)
test.r <- (scaled_test$BOXES)*(max(data$BOXES)-min(data$BOXES))+min(data$BOXES)
rmse.nn <- sqrt(mean((dataTest$BOXES-pr.nn_)^2))
rmse.nn

 plot(dataTest$BOXES,pr.nn_,col='blue',main='Real vs predicted Neural Net',pch=18, cex=0.7)
 abline(0,1,lwd=2)

```



#Create the boosted random forest model
```{r}
model.xgb <- xgb.train(data=xgTrain_box, objective='reg:linear', eval_metric='rmse', booster='gbtree', watchlist = list(train=xgTrain_box, validate=xgVal_box), 
                  early_stopping_rounds=100, nrounds = 100000, num_parallel_tree=20, print_every_n = 20, nthread=4,eta = .1, max_depth = 7)
dataTest.xgb <- build.x(data_formula_boxes, data=dataTest, contrasts = FALSE, sparse = TRUE)

prediction.xgb <- predict(model.xgb, newdata = dataTest.xgb)
plot(dataTest$BOXES,prediction.xgb,col='blue',main='Real vs predicted Boosted Forest',pch=18, cex=0.7)
 abline(0,1,lwd=2)

```




